### ISSUE TITLE
iOS crash on interrupting recognition process 

### ISSUE THREAD

**Issue by orvCiklum** [snapsure-insurance-bot/snapsure-sdk-ios#1]
[crash_log.txt](https://github.com/snapsure-insurance-bot/snapsure-sdk-ios/files/1084873/crash_log.txt)
Hello! Here is a crash log and approximate way to reproduce:
1. Start recognition process
2. Stop it while it wasn't finished
3. Move to another page
4. Lock device
5. Wait some time
6. Unlock device
7. Meet a crash

**Comment by picsure** [comment]
Hi there,
thanks for the bug report. We will inspect this issue as soon as possible.

**Comment by picsure** [comment]
The bug is fixed and the issue is resolved now. Thanks for reporting.
